/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.AccountControl;
import Control.BoxControl;
import Model.Account;
import Model.Box;
import Model.Document;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabriel Guimarães
 */
public class IFRMListBox extends javax.swing.JInternalFrame {

    private Account acc = new Account();
    private ArrayList<Box> boxes = new ArrayList<>();
    private DefaultTableModel dfltBoxes;
    private Box boxClicked = new Box();

    /**
     * Creates new form IFRMListBox
     */
    public IFRMListBox(int id) {
        initComponents();
        this.setDefaultRender();
        this.setAcc(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PNLMain = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBLBoxes = new javax.swing.JTable();
        PNLOptions = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        PNLDocsIn = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TFDocsIn = new javax.swing.JTextPane();

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        TBLBoxes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TBLBoxes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBLBoxes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TBLBoxes.getTableHeader().setReorderingAllowed(false);
        TBLBoxes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBLBoxesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBLBoxes);
        if (TBLBoxes.getColumnModel().getColumnCount() > 0) {
            TBLBoxes.getColumnModel().getColumn(0).setResizable(false);
            TBLBoxes.getColumnModel().getColumn(1).setResizable(false);
            TBLBoxes.getColumnModel().getColumn(2).setResizable(false);
        }

        PNLOptions.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        javax.swing.GroupLayout PNLOptionsLayout = new javax.swing.GroupLayout(PNLOptions);
        PNLOptions.setLayout(PNLOptionsLayout);
        PNLOptionsLayout.setHorizontalGroup(
            PNLOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNLOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PNLOptionsLayout.setVerticalGroup(
            PNLOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNLOptionsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        PNLDocsIn.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Documents In", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(255, 0, 0))); // NOI18N

        TFDocsIn.setEditable(false);
        TFDocsIn.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(TFDocsIn);

        javax.swing.GroupLayout PNLDocsInLayout = new javax.swing.GroupLayout(PNLDocsIn);
        PNLDocsIn.setLayout(PNLDocsInLayout);
        PNLDocsInLayout.setHorizontalGroup(
            PNLDocsInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        PNLDocsInLayout.setVerticalGroup(
            PNLDocsInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLDocsInLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PNLMainLayout = new javax.swing.GroupLayout(PNLMain);
        PNLMain.setLayout(PNLMainLayout);
        PNLMainLayout.setHorizontalGroup(
            PNLMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNLMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PNLOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PNLDocsIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PNLMainLayout.setVerticalGroup(
            PNLMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNLMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                    .addGroup(PNLMainLayout.createSequentialGroup()
                        .addComponent(PNLOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PNLDocsIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PNLMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PNLMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TBLBoxesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBLBoxesMouseClicked
        this.boxClicked = boxes.get(TBLBoxes.getSelectedRow());
        TBLBoxes.clearSelection();
        this.showDocumets();
    }//GEN-LAST:event_TBLBoxesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PNLDocsIn;
    private javax.swing.JPanel PNLMain;
    private javax.swing.JPanel PNLOptions;
    private javax.swing.JTable TBLBoxes;
    private javax.swing.JTextPane TFDocsIn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    private void setAcc(int id) {
        AccountControl accc = new AccountControl();
        this.acc = accc.getAccountById(id);
        this.prepareTable();
    }

    private void prepareTable() {
        this.boxes = BoxControl.listBoxByIdAcc(this.acc.getId());

        this.clearTable();
        this.populateTable();
    }

    private void clearTable() {
        while (TBLBoxes.getRowCount() > 0) {
            DefaultTableModel dm = (DefaultTableModel) TBLBoxes.getModel();
            dm.getDataVector().removeAllElements();
        }
    }

    private void populateTable() {
        this.dfltBoxes = (DefaultTableModel) this.TBLBoxes.getModel();
        for (Box box : boxes) {
            dfltBoxes.addRow(new Object[]{box.getId(), box.getName(), box.getDescription()});
        }
        TBLBoxes.setModel(dfltBoxes);
    }

    private void setDefaultRender() {
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        TBLBoxes.setDefaultRenderer(String.class, centerRenderer);
    }

    private void showDocumets() {
        String txt = "";
        for (Document doc : this.boxClicked.getDocuments()) {
            txt+=doc.getName()+" \n";
        }
    }
}
