/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.AccountControl;
import Control.BoxControl;
import Control.Functions;
import Control.Warnings;
import Model.Account;
import Model.Box;
import Model.Document;
import com.itextpdf.text.DocumentException;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabriel Guimarães
 */
public class IFRMListBox extends javax.swing.JInternalFrame {

    private Account acc = new Account();
    private ArrayList<Box> boxes = new ArrayList<>();
    private DefaultTableModel dfltBoxes;
    private Box boxClicked = new Box();

    /**
     * Creates new form IFRMListBox
     */
    public IFRMListBox(int id) {
        initComponents();
        this.setDefaultRender();
        this.setAcc(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PNLMain = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBLBoxes = new javax.swing.JTable();
        PNLOptions = new javax.swing.JPanel();
        BTNEdit = new javax.swing.JButton();
        BTNOptions = new javax.swing.JButton();
        BTNDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TFShowId = new javax.swing.JTextField();
        TFShowName = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TFShowDescription = new javax.swing.JTextArea();
        PNLDocsIn = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TFDocsIn = new javax.swing.JTextPane();

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        TBLBoxes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TBLBoxes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBLBoxes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TBLBoxes.getTableHeader().setReorderingAllowed(false);
        TBLBoxes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBLBoxesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBLBoxes);
        if (TBLBoxes.getColumnModel().getColumnCount() > 0) {
            TBLBoxes.getColumnModel().getColumn(0).setResizable(false);
            TBLBoxes.getColumnModel().getColumn(1).setResizable(false);
            TBLBoxes.getColumnModel().getColumn(2).setResizable(false);
        }

        PNLOptions.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BTNEdit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BTNEdit.setText("Edit");
        BTNEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEditActionPerformed(evt);
            }
        });

        BTNOptions.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BTNOptions.setText("Options");
        BTNOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNOptionsActionPerformed(evt);
            }
        });

        BTNDelete.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BTNDelete.setText("Delete");
        BTNDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDeleteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Id:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Description:");

        TFShowId.setEditable(false);
        TFShowId.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        TFShowName.setEditable(false);
        TFShowName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        TFShowDescription.setEditable(false);
        TFShowDescription.setColumns(20);
        TFShowDescription.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TFShowDescription.setRows(5);
        jScrollPane3.setViewportView(TFShowDescription);

        javax.swing.GroupLayout PNLOptionsLayout = new javax.swing.GroupLayout(PNLOptions);
        PNLOptions.setLayout(PNLOptionsLayout);
        PNLOptionsLayout.setHorizontalGroup(
            PNLOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNLOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNOptions, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addComponent(BTNEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addComponent(BTNDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addGroup(PNLOptionsLayout.createSequentialGroup()
                        .addGroup(PNLOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PNLOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFShowId)
                            .addComponent(TFShowName)))
                    .addGroup(PNLOptionsLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                .addContainerGap())
        );
        PNLOptionsLayout.setVerticalGroup(
            PNLOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNLOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNLOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TFShowId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNLOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFShowName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNOptions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNDelete)
                .addContainerGap())
        );

        PNLDocsIn.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Documents In", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(255, 0, 0))); // NOI18N

        TFDocsIn.setEditable(false);
        TFDocsIn.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(TFDocsIn);

        javax.swing.GroupLayout PNLDocsInLayout = new javax.swing.GroupLayout(PNLDocsIn);
        PNLDocsIn.setLayout(PNLDocsInLayout);
        PNLDocsInLayout.setHorizontalGroup(
            PNLDocsInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        PNLDocsInLayout.setVerticalGroup(
            PNLDocsInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLDocsInLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PNLMainLayout = new javax.swing.GroupLayout(PNLMain);
        PNLMain.setLayout(PNLMainLayout);
        PNLMainLayout.setHorizontalGroup(
            PNLMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNLMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PNLOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PNLDocsIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PNLMainLayout.setVerticalGroup(
            PNLMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNLMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                    .addGroup(PNLMainLayout.createSequentialGroup()
                        .addComponent(PNLOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PNLDocsIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PNLMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PNLMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TBLBoxesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBLBoxesMouseClicked
        this.boxClicked = boxes.get(TBLBoxes.getSelectedRow());
        TFShowDescription.setText(this.boxClicked.getDescription());
        TFShowId.setText(this.boxClicked.getId() + "");
        TFShowName.setText(this.boxClicked.getName());
        this.showDocumets();
    }//GEN-LAST:event_TBLBoxesMouseClicked

    private void BTNDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDeleteActionPerformed
        if (boxClicked.getId() > 0) {
            if (boxClicked.getDocuments().size() != 0) {
                Warnings.wrngCannotDeleteBoxCauseDocs();
            } else {
                if (Warnings.wrngConfirmDelete() == 0) {
                    if (Warnings.wrngTypeYourPassword().equals(this.acc.getPassword())) {
                        if (BoxControl.deleteBox(boxClicked.getId()) == false) {
                            Warnings.wrngDeleteDocumentSuccess();
                            this.restart();
                        } else {
                            Warnings.wrngDeleteDocumentFail();
                        }
                    } else {
                        Warnings.wrngIncorrectPassword();
                    }
                } else {

                }
            }
        } else {
            Warnings.wrngNoSelection();
        }
    }//GEN-LAST:event_BTNDeleteActionPerformed

    private void BTNEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNEditActionPerformed

    private void BTNOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNOptionsActionPerformed
        ArrayList<Boolean> boos = Warnings.wrngOptions();
        if (boos.get(0)) {
            if (boxClicked.getId() > 0) {
                try {
                    Functions.generatePDFCapeToBox(acc, boxClicked);
                } catch (FileNotFoundException ex) {
                    Warnings.wrngSomethingWentWrong(ex);
                } catch (DocumentException ex) {
                    Warnings.wrngSomethingWentWrong(ex);
                }
            } else {
                Warnings.wrngNoSelection();
            }
        }
        if (boos.get(1)) {
            if (boxClicked.getId() > 0) {
                try {
                    Functions.generatePDFToBoxsDocments(acc, boxClicked);
                } catch (FileNotFoundException ex) {
                    Warnings.wrngSomethingWentWrong(ex);
                } catch (DocumentException ex) {
                    Warnings.wrngSomethingWentWrong(ex);
                }
            } else {
                Warnings.wrngNoSelection();
            }
        }
        if (boos.get(2)) {
            if (boxes.size()!=0) {
                try {
                    Functions.generatePDFAllBoxs(boxes, acc);
                } catch (FileNotFoundException ex) {
                    Warnings.wrngSomethingWentWrong(ex);
                } catch (DocumentException ex) {
                    Warnings.wrngSomethingWentWrong(ex);
                }
            } else {
                Warnings.wrngNoBoxes();
            }
        }
    }//GEN-LAST:event_BTNOptionsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNDelete;
    private javax.swing.JButton BTNEdit;
    private javax.swing.JButton BTNOptions;
    private javax.swing.JPanel PNLDocsIn;
    private javax.swing.JPanel PNLMain;
    private javax.swing.JPanel PNLOptions;
    private javax.swing.JTable TBLBoxes;
    private javax.swing.JTextPane TFDocsIn;
    private javax.swing.JTextArea TFShowDescription;
    private javax.swing.JTextField TFShowId;
    private javax.swing.JTextField TFShowName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
    private void setAcc(int id) {
        AccountControl accc = new AccountControl();
        this.acc = accc.getAccountById(id);
        this.prepareTable();
    }

    private void prepareTable() {
        this.boxes = BoxControl.listBoxByIdAcc(this.acc.getId());

        this.clearTable();
        this.populateTable();
    }

    private void clearTable() {
        while (TBLBoxes.getRowCount() > 0) {
            DefaultTableModel dm = (DefaultTableModel) TBLBoxes.getModel();
            dm.getDataVector().removeAllElements();
        }
    }

    private void populateTable() {
        this.dfltBoxes = (DefaultTableModel) this.TBLBoxes.getModel();
        for (Box box : boxes) {
            dfltBoxes.addRow(new Object[]{box.getId(), box.getName(), box.getDescription()});
        }
        TBLBoxes.setModel(dfltBoxes);
    }

    private void setDefaultRender() {
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        TBLBoxes.setDefaultRenderer(String.class, centerRenderer);
    }

    private void showDocumets() {
        String txt = "";
        for (Document doc : this.boxClicked.getDocuments()) {
            txt += doc.getName() + " \n";
        }
        TFDocsIn.setText(txt);
    }

    private void restart() {
        IFRMListBox ilb = new IFRMListBox(this.acc.getId());
        javax.swing.plaf.InternalFrameUI ifu = ilb.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) ifu).setNorthPane(null);
        this.getParent().add(ilb);
        try {
            ilb.setMaximum(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
        ilb.show();
        this.dispose();
    }
}
